package state

import (
	"fmt"
	"strings"

	"github.com/rancher/rke2-patcher/internal/components"
	"github.com/rancher/rke2-patcher/internal/kube"
	"github.com/rancher/rke2-patcher/internal/patcher"
)

const helmChartConfigNamespace = "kube-system"

// HelmChartConfigName returns the HelmChartConfig a component's patch was written to.
// Several components share a chart (e.g. rke2-dns-node-cache -> rke2-coredns).
func HelmChartConfigName(componentName string) string {
	if component, err := components.Resolve(componentName); err == nil {
		return component.HelmChartConfigName
	}
	return componentName
}

// RevertEntry removes the values generated by the patcher for this entry from its
// HelmChartConfig, leaving any other values untouched. It returns false when there was
// nothing to revert. The HelmChartConfig is never deleted so RKE2 re-renders the chart
// with its bundled defaults.
func RevertEntry(entry Entry) (bool, error) {
	return RevertEntryWith(entry, kube.GetHelmChartConfigByIdentity, kube.ApplyHelmChartConfig)
}

// HelmChartConfigGetter and HelmChartConfigApplier match the kube package functions
type (
	HelmChartConfigGetter  func(name string, namespace string) (*kube.HelmChartConfigObject, error)
	HelmChartConfigApplier func(content string, resourceVersion string) error
)

// RevertEntryWith is RevertEntry with injectable HelmChartConfig access
func RevertEntryWith(entry Entry, get HelmChartConfigGetter, apply HelmChartConfigApplier) (bool, error) {
	generatedValuesContent := strings.TrimSpace(entry.GeneratedValuesContent)
	if generatedValuesContent == "" {
		return false, nil
	}

	existing, err := get(HelmChartConfigName(entry.Component), helmChartConfigNamespace)
	if err != nil {
		return false, fmt.Errorf("failed to get HelmChartConfig for reconciliation: %w", err)
	}
	if existing == nil {
		return false, nil // nothing to reconcile
	}

	existingContent := strings.TrimSpace(existing.Content)
	if existingContent == "" {
		return false, nil
	}

	updatedContent, err := patcher.SubtractPatcherValuesContent(existingContent, generatedValuesContent)
	if err != nil {
		return false, fmt.Errorf("failed to strip patcher values: %w", err)
	}

	if err := apply(updatedContent, existing.ResourceVersion); err != nil {
		return false, fmt.Errorf("failed to apply reconciled HelmChartConfig: %w", err)
	}

	return true, nil
}
