apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rke2-patcher
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "pods/log", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["helm.cattle.io"]
    resources: ["helmcharts", "helmchartconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["upgrade.cattle.io"]
    resources: ["plans"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets"]
    verbs: ["get", "list", "watch"]